service: u-control-backend

frameworkVersion: '4'

# Serverless Framework Configuration
configValidationMode: error

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  deploymentBucket:
    name: ${env:AWS_DEPLOYMENT_BUCKET, 'u-control-906421059987'}
    serverSideEncryption: AES256
  environment:
    STAGE: ${self:provider.stage}
    PG_HOST: ${env:PG_HOST}
    PG_PORT: ${env:PG_PORT}
    PG_DATABASE: ${env:PG_DATABASE}
    PG_USER: ${env:PG_USER}
    PG_PASSWORD: ${env:PG_PASSWORD}
    JWT_SECRET: ${env:JWT_SECRET}
  # IAM permissions for external services (PostgreSQL, S3, etc.)
  # No specific IAM permissions needed for external PostgreSQL database

functions:
  hello:
    handler: src/handlers/hello.handler
    events:
      - http:
          path: hello
          method: get
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001
    host: 0.0.0.0
